### ISSUE TITLE
试一下功能

### ISSUE THREAD

**Issue by jiacongjia** [phodal/articles#50]
诗与美
Nature and laws lay hid in light; God said “Let Newton be” and all was light.这句赞美牛顿的（）被译为：道法自然，旧藏玄冥。天生牛顿，万物生明。

读至此处，甚是惊艳，翻译之尊，信达雅三字可谓做到淋漓尽致，其中意味，颇有感慨。
私下试过使用有道词典进行翻译，其功能只不过是死板机械地生搬硬套罢了，直译出来的句子，毫无美感可言,再尝试更多古句译英，同样是毫无生气的字符相连。
美的存在是人类最引以为傲的一点，它不单单是视觉上的享受，更是从灵魂角度的契合。让人如沐春风，滋养在和煦春日暖阳的大草原里，恣意翻滚，不觉无趣。
机器在此方面终归是有所欠缺的，0和1组成的世界，或许是无法容忍下美好的错误的，没有了错误便很难发现美，多少令人赞叹的美，都是在一个个错误中被人记住，流芳千古。

**Comment by phodal** [comment]
Hi @jiacongjia，文字功底不错哈~~

不过，这里主要是为来发我的文章，所以我要关了这个 issue 哈。
